### PR TITLE
Fix `Instance` example

### PR DESCRIPTION
**Pull request by GabrielMajeri**
This pull request fixes an example in the documentation. Previously it didn't build because of ownership issues.

This changes the `Instance::new` / `Instance::with_loader` functions to take an `Iterator` to `Item = &'a str`, instead of `Item = &'a &'a str`.

It also replaces `unwrap` with `?`.

### CODE REVIEW

**Comment by tomaka** [comment]
The problem is that this is a breaking change.

**Comment by GabrielMajeri** [comment]
@tomaka It is, however there is probably little code out there which uses layers.

The only layers which exist right now are the validation layers, and the docs recommend enabling them using environment variables, not manually.

We're just future-proofing the code here, to make it easier to use when layers become more popular.

In other words, most code would be using `None` for layers, meaning no breakage.

P.S.: should I also update the changelog in this pull request, mentioning this change?

**Comment by rukai** [comment]
This looks good to me. However, it needs an entry in the changelog before I can merge it.

**Comment by rukai** [comment]
Thanks

**Pull request merged**
