### PR TITLE
Release 0.21.0

### PR DESCRIPTION
**Pull request by Eliah-Lakhin**
Versions bump and changelogs update for new release.

### CODE REVIEW

**Comment by Eliah-Lakhin** [comment]
@Arc-blroth, @Rua, @danielzgtg There are a number of changes accumulated in the current `master` branch, and I decided to release them first before merging your recent PRs. Just want to keep releases a bit more "atomic".

But I keep an eye at your Pull Requests and will review them very soon. Some of that Pull Requests contain breaking changes, so releasing them all together would be a bit more risky than separate into the next release.

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 May I ask you to help me with publishing to crates.io, please?

Pierre gave me an access to crates.io with my @Eliah-Lakhin Github account, but I can't use it to login to crates.io at this moment due to extra permissions crates.io is requesting through Github to one of organizations I have a membership in with very restrictive NDA rules.

**Comment by Rua** [comment]
#1498 could be merged without breaking anything.

**Comment by Eliah-Lakhin** [comment]
@Rua True. I just think we have too many stuff in this release. I will certainly merge it right after this release. Thank you!

**Comment by AustinJ235** [comment]
I publish tn after work it'll be another 8 hrs or so.

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 Thank you so much!

**Pull request merged**
