### PR TITLE
Changelog entry for PR #1410 and turning off Travis Linux Nightly build job

### PR DESCRIPTION
**Pull request by Eliah-Lakhin**
Reopens #1422

### CODE REVIEW

**Comment by AustinJ235** [comment]
You may have to push a dummy commit to trigger travis. Sometimes travis doesn't like to trigger.

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 Done. https://travis-ci.org/github/vulkano-rs/vulkano/builds/734538111 It passed tests, but the PR is still blocked.

**Comment by Eliah-Lakhin** [comment]
@tomaka I'm sorry for disturbing you, but Travis is completely broken. It blocks all currently pending PRs, even those that successfully passing actual checks, like this one: https://travis-ci.org/github/vulkano-rs/vulkano/builds/734538111

Can you give me an advice on what I can do to help resolving it?

Thank you.

**Comment by tomaka** [comment]
I'm a clueless as to what is happening. As a work-around I've disabled the necessity to have the CI pass in order to merge PRs.

**Comment by Eliah-Lakhin** [comment]
@tomaka Thank you very much!

**Comment by AustinJ235** [comment]
@tomaka I did manage to get githubs ci to work if you have interest on switching the repo to that. I just haven't made a pull request with it yet. I believe github also supports encrypted keys if you wanted to add one to the project so I could add a trigger for publishing also.

**Pull request merged**
