### PR TITLE
Split `AutoCommandBuffer` into primary and secondary

### PR DESCRIPTION
**Pull request by Rua**
* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [x] Updated documentation to reflect any user-facing changes - in this repository
* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.
* [x] Ran `cargo fmt` on the changes

The `AutoCommandBuffer` is split into `PrimaryAutoCommandBuffer` and `SecondaryAutoCommandBuffer`, and the trait `CommandBuffer` is also split into `PrimaryCommandBuffer` and `SecondaryCommandBuffer`. `AutoCommandBufferBuilder` is still one type, but it has a type parameter for which type it will build.

I've also renamed `Kind` and changed how it works a little, so that it now holds a `CommandBufferInheritance` for secondary command buffers. The `SecondaryCommandBuffer::inheritance` trait method returns this value.

Pros:
- It turns out that there are actually no functions in Vulkano that can accept either type of command buffer. Functions can now specifically ask for one type or the other, giving the wrong type is a compile-time error. This removes a runtime check.
- Likewise, the trait methods of `CommandBuffer` only make sense for primary _or_ secondary command buffers, the only one that works for both is `inner`.
- Some methods on `AutoCommandBufferBuilder` are now only implemented for `AutoCommandBufferBuilder<PrimaryAutoCommandBuffer>`, so this removes a runtime check.

Cons:
- It's now a bit harder to write a function that works for both primary and secondary command buffer builders. You'd have to make it a generic function. Time will tell if this proves to be an obstacle?

### CODE REVIEW

**Comment by Rua** [comment]
I don't really understand why this branch is including a whole lot of commits that have already been merged. But I think it's ok? Git is still a bit magic to me.

**Comment by Eliah-Lakhin** [comment]
@Rua This is not a strong requirement to accept this PR, but I detected false-positive issues with the IntelliJ Idea Rust plugin. This is a minimal example:

```rust
use std::sync::Arc;
use vulkano::command_buffer::{AutoCommandBufferBuilder, PrimaryAutoCommandBuffer};
use vulkano::device::{Device, Queue};

fn foo(device: Arc<Device>, queue: Arc<Queue>) -> PrimaryAutoCommandBuffer {
    AutoCommandBufferBuilder::primary(device, queue.family())
        .unwrap()
        .build()
        .unwrap()
}
```

This code compiles perfectly fine with Rust 1.51, there are no compile-time errors, but Idea plugin(I tried nightly and stable versions both) cannot resolve `build` method correctly:

Screenshot from 2021-04-04 09-00-17

Although, this error normally should be addressed to the plugin developers, I think this is an indication of some mess in the Vulkano internal reexports. And since Idea plugin is widely used by the users, I want to ask you to debug your code a little further and try to fix this issue. Even if this is a blame of Idea plugin, it would be good if we align our code such that it would be more ergonomic for Vulkano users.

**Comment by Rua** [comment]
The `build` method is implemented in this block
```Rust
impl<P> AutoCommandBufferBuilder<PrimaryAutoCommandBuffer<P::Alloc>, P>
where
    P: CommandPoolBuilderAlloc,
```
I'm not really sure what the plugin is getting confused about, because at least in Rust this makes perfect sense. As you say, the compiler figures it out just fine. But Idea appears to not recognise that the builder matches this `impl` block, somehow. I don't know what to do about that other than poke the developers.

**Comment by Eliah-Lakhin** [comment]
@Rua ok, it probably will be difficult to fix, and after talking to some people I figured out that the Idea plugin is not that widely used these days, so we probably shouldn't relay on it that much. Please resolve merging conflicts, and I will proceed with merging. Thank you!

**Comment by Rua** [comment]
Done.

**Comment by Eliah-Lakhin** [comment]
@Rua Merged :+1:

 > Looks like someone already made an issue referencing this too, nice!

Yes, I reported it to developers in a chat, and they opened the issue :) Hope it will be resolved eventually, but I believe IDE plugin shouldn't be a blocker to push our project forward.

**Pull request merged**
