### PR TITLE
Fix OutOfHostMemory error in examples

### PR DESCRIPTION
**Pull request by theotherphil**
* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [x] Updated documentation to reflect any user-facing changes - in this repository
* [x] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.

Fixes https://github.com/vulkano-rs/vulkano/issues/1217

### CODE REVIEW

**Comment by AustinJ235** [comment]
Mind adding comments saying this is only necessary with systems using nvidia or on macos?

**Comment by theotherphil** [comment]
Done. (I don't have access to any other systems to test this claim, so I'll take your word for it!)

**Comment by AustinJ235** [comment]
Can you update your comments to refer to https://github.com/vulkano-rs/vulkano/issues/1247 instead.

**Comment by theotherphil** [comment]
Done

**Pull request merged**
