### PR TITLE
Feature: Create a Surface from a RawWindowHandle

### PR DESCRIPTION
**Pull request by nifker**
* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [x] Updated documentation to reflect any user-facing changes - in this repository
* [x] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.
* [x] Ran `cargo fmt` on the changes

### CODE REVIEW

**Comment by nifker** [comment]
Im open to feedback on this.

**Comment by nifker** [comment]
Just to ensure you get notified about this PR: @AustinJ235

**Comment by AustinJ235** [comment]
Seems something that is a good change overall. Travis CI is being derpy again so whenever that decides to work. I feel this would make other options available aside from winit. Winit tends to have a lot of breakage yet and isn't ideal for all.

**Comment by nifker** [comment]
@AustinJ235 So were basically gonna wait for Travis CI to work again?

**Comment by AustinJ235** [comment]
You may have to push another commit for it to work since it hasn't detected your last one.

**Comment by nifker** [comment]
Just did so and it worked

**Pull request merged**
