### PR TITLE
Support surface creation with winit >= 0.20 

### PR DESCRIPTION
**Pull request by nifker**
Compilation test under Windows, OSX, iOS and Android desired.
I can remove the version change is desired.

### CODE REVIEW

**Comment by nifker** [comment]
Seems like the examples need to be changed too - Should this be done already?

**Comment by nifker** [comment]
Ok the only remaining issues are from the formatting - Seems like cargo fmt doesnt work here anymore with: "unknown variant `Visual`, expected one of `Compressed`, `Tall`, `Vertical` for key `fn_args_layout".

**Comment by Eliah-Lakhin** [comment]
@mitchmindtree, @rukai Can you review and merge, please?

**Comment by AustinJ235** [comment]
I think this should probably be a major version bump and not a minor.

**Comment by AustinJ235** [comment]
Didn't need to bump the examples version, but it doesn't really matter. Another conflict popped up however.

**Comment by nifker** [comment]
I merged the new changes into my repo again. Should fine then.

**Pull request merged**
