### PR TITLE
Integrate latest vk.xml changes

### PR DESCRIPTION
**Pull request by 0xcaff**
## Overview

Pulls in the vk.xml used in ash 0.38 (https://github.com/KhronosGroup/Vulkan-Headers/blob/38899bf60605f0a2c50f7968e5c4c9826a824683/registry/vk.xml) adding stuff to autogen to get it compiling.

## Merge Order

This is ready to merge. It depends on:

1. https://github.com/vulkano-rs/vulkano/pull/2512
2. https://github.com/vulkano-rs/vulkano/pull/2511
3. https://github.com/vulkano-rs/vulkano/pull/2510

all of which are merged.

## Changelog
```markdown
### Additions
- Update vk.xml to [Vulkan-Headers@38899bf](https://github.com/KhronosGroup/Vulkan-Headers/blob/38899bf60605f0a2c50f7968e5c4c9826a824683/registry/vk.xml) to match version used in ash 0.38
```

### CODE REVIEW

**Comment by 0xcaff** [comment]
I've updated it here, https://github.com/vulkano-rs/vulkano/pull/2513/commits/a60ab3a5b57596490c006984542840578d1a2657

How does this look?

**Comment by Rua** [comment]
I meant defining them using the `vulkan_enum!` and `vulkan_bitflags!` macros, following the definitions in the Vulkan spec:
- https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkLayeredDriverUnderlyingApiMSFT.html
- https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceSchedulingControlsFlagsARM.html

**Comment by 0xcaff** [comment]
ahh I see ok good idea, updated!

**Comment by Rua** [comment]
Thanks!

**Pull request merged**
