### PR TITLE
examples: bin; pipeline_caching, add underscore for unused var

### PR DESCRIPTION
**Pull request by Horki**
* [ ] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [ ] Updated documentation to reflect any user-facing changes - in this repository
* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.
* [x] Ran `cargo fmt` on the changes

@tomaka 
Small update (added underscore) on unused `pipeline` var (bin / pipeline caching)

### CODE REVIEW

**Comment by Eliah-Lakhin** [comment]
@Horki This is probably not the only linter's warning in examples. May I ask you to review the entire set of examples and put corresponding fixes of linter?

**Comment by Horki** [comment]
@Eliah-Lakhin this was the *only* warning when I run `cargo build`

**Comment by Eliah-Lakhin** [comment]
@Horki ok, `cargo fix` showing the same output on my end. Merging...

**Comment by Eliah-Lakhin** [comment]
Merged. Thank you!

**Comment by Horki** [comment]
@Eliah-Lakhin :+1:

**Pull request merged**
