### PR TITLE
Add example `immutable-buffer-initialization`

### PR DESCRIPTION
**Pull request by kazzix14**
This is related to #1138.
Because no detailed documentation or example exists, It took time for me to figure out how I can initialize immutable buffers. So I added an example about how to initialize immutable buffers.

### CODE REVIEW

**Comment by AustinJ235** [comment]
Don't worry about the failed build status. travis ci builds for windows are currently failing. My pull request for pipeline barrier fix modifies the travis build. Ill have you remege when that goes through. Just want to give the code another look before merging.

Otherwise I see nothing wrong with your example and will go ahead with a merge after mine goes through.

**Review by Eliah-Lakhin — APPROVED** [review]

**Review by Eliah-Lakhin — CHANGES_REQUESTED** [review]
@kazzix14 Can you merge the recent upstream master onto the feature branch and fix API usage issues, please? Your commit has outdated a little with the recent API changes, but I will be happy to review and merge it relatively quickly once it passes Travis tests.

Thank you, and I'm sorry for delay with review.

**Review by Eliah-Lakhin — APPROVED** [review]

**Comment by Eliah-Lakhin** [comment]
@kazzix14 My apology, I totally forgot about your Pull Request. :(

I didn't have maintainers access previously, but the example is really useful for us. Thank you for your help! PR is merged :+1:

For future reference. Please don't hesitate to enforce my attention to the long standing PRs such as this one by mentioning me in the comments. I'm trying to review PRs in relatively reasonable time, but sometimes I can miss something unfortunately.

Thanks again!

**Comment by Rua** [comment]
There's a few compile errors in this code now, because some changes have been merged since it was written.

**Comment by Eliah-Lakhin** [comment]
@Rua Yes, already noticed them. Trying to fix...

Two of these issues are just earlier API migrations and are easy to fix, and one might be related to Image/View migration made recently: https://github.com/vulkano-rs/vulkano/runs/2106702207?check_suite_focus=true#step:3:381 What do you think?

**Comment by Rua** [comment]
The first error is #1443, the other two are #1480.

**Comment by Eliah-Lakhin** [comment]
ok. The issue resolved now.

**Pull request merged**
