### PR TITLE
Unlock images correctly on Err

### PR DESCRIPTION
**Pull request by Gosuo**
If the CommandBuffer encountered an error in the lock_submit function,
it would unlock all the previously locked resources and return the
error. It would unlock all the images with a None value which would
panic in an assertion in the unlock method of the images. Now it checks
for the final_layout and unlocks the image this way.
This change should help with the panics mentioned in #1441 and #1447.
With this fix, it should return the error that is occurring instead of
panicking.

* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
~~* [ ] Updated documentation to reflect any user-facing changes - in this repository~~
~~* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.~~
* [x] Ran `cargo fmt` on the changes

### CODE REVIEW

**Comment by Gosuo** [comment]
@Eliah-Lakhin Well, I'm open for a review here actually. I don't know if this is correct, but the images are unlocked the same way in the `unlock` method of the buffer.

The panics of the asserts in the mentioned issues disappear with this fix though.

**Comment by Eliah-Lakhin** [comment]
@Gosuo Can you add an entry to the changelog file, please?

**Comment by Gosuo** [comment]
@Eliah-Lakhin Oh, I thought the change log is only for user-facing changes, but I can add an entry as soon I have time.

**Comment by Eliah-Lakhin** [comment]
@Gosuo Well, this is an actual(and important!) bug fix affecting the end-user experience, so I would log it anyway :)

**Comment by Gosuo** [comment]
@Eliah-Lakhin Added the information to the changelog.

**Comment by Eliah-Lakhin** [comment]
@Gosuo PR merged. Thank you very much for this fix! Now it will unblock a number of higher level features progress.

**Comment by faulesocke** [comment]
I guess this is not correct. When a command buffer execution fails (which should never happen with vulkano), it is unspecified what the contents and layout of the images it touched are.

However in the unlock methods parameter you specify what the layout is after command buffer execution and I guess the `None` value is exactly for this purpose: Telling the image that the layout is unknown because of an execution error.

The solution here is obvious: Fix the actual error that causes the command buffer execution to fail.

**Comment by Gosuo** [comment]
@faulesocke But the actual underlying Vulkan buffer wasn't executed at that point. It just locked the needed resources from the Rust point of view. That way the image wasn't touched at that point, or am I wrong?
Sounds logical though that the current unlocks with the final layout are not correct. Maybe unlock it with the initial layout?

**Comment by faulesocke** [comment]
Well but when nothing was executed the image is certainly not in the desired final layout, is it?

**Comment by Gosuo** [comment]
What do you suggest? Revert the change?
Your example in #1447 fails at the insertion introduced in #1444, so I'm not sure how to test this further.

**Comment by faulesocke** [comment]
Not sure what to do. This needs further investigation. I might have time for it during the weekend.

**Comment by Eliah-Lakhin** [comment]
@faulesocke, @Gosuo Please keep updating me on the issue progress. These features are completely above of my current understanding of Vulkano internals, so I will leave it to your hands.

**Pull request merged**
