### PR TITLE
Update shaderc to 0.6 in order to significantly reduce compile-times …

### PR DESCRIPTION
**Pull request by Abendstolz**
…on (Arch/Void)Linux again by linking towards shared libraries

* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users

@mitchmindtree fyi

### CODE REVIEW

**Comment by mitchmindtree** [comment]
@Abendstolz nice! I think using pre-installed libraries was already active in 0.5, but at least this gets it working again on Arch and Void :+1:

Could you also add a `shaderc-build-from-source` feature to `vulkano-shaders` which enables the `shaderc/build-from-source` feature? I just realised this feature is currently inaccessible via `vulkano-shaders` and might save us temporarily if shaderc's linking to pre-built libraries breaks again in the future.

**Comment by Abendstolz** [comment]
@mitchmindtree sure thing. Done in https://github.com/vulkano-rs/vulkano/pull/1226/commits/5db99c837330f3a0656e9c6827a1fde24421465b

**Comment by mitchmindtree** [comment]
Thanks a lot @Abendstolz - it looks like travis is just complaining about some trailing whitespace now, but after that's fixed I'd be happy to merge!

@rukai would you mind if we published 0.14 after this as another emergency patch to make it possible for Arch/Void users to build vulkano-shaders? Maybe we can also include #1227 and #1225, though I'm not well versed enough to understand if #1225 is correct/safe.

**Comment by rukai** [comment]
Sure, feel free to publish 0.14 if need be, the website would additionally need to be updated.

I cannot review PRs as i am already using my free time to work on gfx Hal/wgpu stack. Sorry. It might be a simple change but it's hard to tell without investing a lot of time in the first place.

**Comment by AustinJ235** [comment]
@rukai I'd like to see this go through and a version published, my projects are still on vulkano 11.1 due to the linking errors with shaderc. That issue is solved by this pull request.

**Comment by m4b** [comment]
can this be emergency pushed? basically all vulkano projects are broken now on archlinux et. al

**Comment by rukai** [comment]
You can workaround it by adding the build-from-source feature to shaderc

 Can @abendstolz fix the CI errors? Then I can proceed with an emergency release

**Comment by Abendstolz** [comment]
@rukai or @mitchmindtree go for it ;)

**Pull request merged**
