### PR TITLE
Goodbye vk-sys

### PR DESCRIPTION
**Pull request by gurchetansingh**
It's dead code at this point.  Those wishing to continue to use it can use older releases of Vulkano.

2. [ X] Please put changelog entries **in the description of this Pull Request**
   if knowledge of this change could be valuable to users. No need to put the
   entries to the changelog directly, they will be transferred to the changelog
   files(`CHANGELOG_VULKANO.md` and `CHANGELOG_VK_SYS.md`)
   by maintainers right after the Pull Request merge.

    * Entries for Vulkano changelog:
        - None
        -
    * Entries for VkSys changelog:
        - None, but deleted CHANGELOG_VK_SYS

### CODE REVIEW

**Comment by gurchetansingh** [comment]
CC: @Eliah-Lakhin @Rua

**Comment by AustinJ235** [comment]
I don't know if we should completely remove it. There may be someone out there looking to maintain these bindings or aren't ready to switch to another alternative yet. I think it be a good idea to move this to another repository or just leave it dormant in this repo. Downside of switching it to another repo would be that all the commit history wouldn't show up on that repo.

@Eliah-Lakhin we do seem to have permission to create repo's under the org.

**Comment by Eliah-Lakhin** [comment]
@gurchetansingh At this point I propose to keep hosting of vk-sys under the main Vulkano github repo. In case someone is still using it, and in case we(by some reasons) will have to revert back by vk-sys. At least until we release this migration to cargo, and get some feedback from the users, I would keep it's code here.

**Comment by Eliah-Lakhin** [comment]
At some point maybe we will remove it and/or migrate somewhere, but I would prefer to do everything more carefully and iteratively :)

**Comment by gurchetansingh** [comment]
Ack.  I'll keep the PR up until the time is right to remove it.

**Comment by Rua** [comment]
The Ash migration is now 3 months old, and I don't think there have been significant issues. I think this may be worth revisiting?

**Comment by gurchetansingh** [comment]
rebased in case it's time to merge

**Comment by AustinJ235** [comment]
`vk-sys` has been moved! You can now find it here: https://github.com/vulkano-rs/vk-sys

This is a fork from the last commit that touched this code, and I stripped it down.

**Pull request merged**
