### PR TITLE
 Add from_handle constructors for various Vulkan object types. #1935 

### PR DESCRIPTION
**Pull request by p3t3rix**
Add from_handle functions so there is a way to use ash directly.

### CODE REVIEW

**Comment by p3t3rix** [comment]
I started by looking for stuff that implements VulkanObject and had a new() function. Not sure if there is a common trait one could extract/implement to make this a bit more streamlined. 
Also as it is now i am not sure there is a consistent direction as for some things we let the user take all the responsibility and others where there is still validation inside (RenderPass for example).
Another thing where i am unsure is how should we handle things like ShaderModule or Buffer. UnsafeBuffer could be constructed but how do we (and should we) handle others that use it internally ?

**Comment by Rua** [comment]
For `RenderPass`, you could extract the code that calculates `views_used` and use that directly, without any of the validation code that surrounds it. I think this code should do it:
```rust
let views_used = subpasses.iter().map(|subpass| u32::BITS - subpass.view_mask.leading_zeros()).max::<u32>();
```

For buffers and images, creating `UnsafeBuffer` and `UnsafeImage` is enough I think. Further adjustments may be needed later but we can do that when it comes to that point. `ShaderModule` probably needs more thought, so you can skip that one for now.

**Comment by p3t3rix** [comment]
I am not sure if i forgot some files, for the following structs i was not sure what to do:
- ShaderModule 
- GraphicsPipeline
- ComputePipeline 
- PipelineCache (not needed as far as i am concerned)
- DeviceMemory
- Instance
- Device
- UnsafeDescriptorSet (has it already under new() but not public )
- UnsafeCommandPoolAlloc
- UnsafeCommandBuffer

for some cases i duplicated logic because the validate method returned stuff (e.g. UnsafeImage).

**Comment by Rua** [comment]
This is very good already, thanks!

In the past, I made some validation functions return values, and in some cases the `Info` struct is also modified, but in hindsight I think this was a mistake. In the future we may want to add the ability to bypass the validation, and everything else should still work if the validation function isn't called. That means the validation functions should all be made read-only at some point, and return only the error. You don't have to do anything about this, just noting that it was a historical oversight on my part.

**Comment by p3t3rix** [comment]
No problem, such is the life with codebases that grow, at some point you look back and think about all the things you would/could do better with the current knowledge 😄 
Also thank you for being so responsive and supportive.

How should we tackle the other points and did i miss some important structs ? Or should i mark this PR ready and the rest is handled in different issues?

**Comment by Rua** [comment]
I think this can be merged as it is. The remaining types can be tackled another time, they probably warrant more individual attention and discussion.

**Pull request merged**
