### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by GabrielMajeri**
This pull request updates dependencies for all the crates to the latest versions.

### CODE REVIEW

**Comment by LPGhatguy** [comment]
Winit 0.11 came out since this PR was created; it causes no breaking changes with Vulkano.

**Comment by tomaka** [comment]
It *does* cause a breaking change because winit is unfortunately exposed in the API.

**Comment by tomaka** [comment]
Please add an entry in CHANGELOG.md and then I'll merge!

**Comment by tomaka** [comment]
Releasing a version doesn't cost much, we can just release 0.9 :)

**Pull request merged**
