### PR TITLE
Add a `reinterpret` function to `BufferSlice`

### PR DESCRIPTION
**Pull request by Limeth**
* [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
* [x] Updated documentation to reflect any user-facing changes - in this repository
* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.

This function allows the user to "view" the buffer as containing data of a different type. It can be useful when a buffer contains multiple types of data.

### CODE REVIEW

**Comment by rukai** [comment]
Please include a doc comment for this function explaining what it does and include a `# safety` section explaining the safety requirements of using this function.

**Comment by Limeth** [comment]
@rukai Done, let me know if there's anything else I should do.

**Comment by Limeth** [comment]
Doesn't work on nightly, huh. The macro shouldn't be necessary anyway.

**Comment by rukai** [comment]
Thanks

**Pull request merged**
