### PR TITLE
Publish 0.12.0 of `vulkano`, `vulkano-win` and `vulkano-shaders`.

### PR DESCRIPTION
**Pull request by mitchmindtree**
Also updates the CHANGELOG to include the image layout transition
improvements.

cc @rukai it might finally be that time :)

-----

* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* ~Updated documentation to reflect any user-facing changes - in this repository~
* ~Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR~.

### CODE REVIEW

**Comment by m4b** [comment]
I’m ok with merging this because I want the winit update but just FYI pretty sure the image layout transitions broke me, or at least regressed. I can post more details later if I get time, but since it’s only a visual regression/breakage and I haven’t identified yet if I’m doing something weird (don’t think so!) we should just merge; just wanted to add this before I forgot :)

**Comment by mitchmindtree** [comment]
It seems the macOS stable travis build timed out, but the other builds seem to be fine.

@m4b ah interesting - if you decide to create an issue about it please cc @freesig and I as we'd be curious to investigate! One thing that comes to mind that might be worth trying - have you removed all manual cases of specifying `initial_layout` and `final_layout` in your `renderpass!` declarations? In theory, vulkano should be able to work these out automatically now, whereas in the past you kind of had to add them sometimes as a hack to work around layout transitions that couldn't be inferred automatically.

**Comment by rukai** [comment]
I'm happy to do a release now, just checking for low hanging fruit that should be thrown in.

**Comment by rukai** [comment]
You should do a PR to the guide to update the version number used.

**Pull request merged**
