### PR TITLE
Initial YUV and external memory support

### PR DESCRIPTION
**Pull request by gurchetansingh**
CC: @AustinJ235 @Eliah-Lakhin @rukai

### CODE REVIEW

**Comment by gurchetansingh** [comment]
Forgot the tasklish:

- [x] Added an entry to CHANGELOG_VULKANO.md or CHANGELOG_VK_SYS.md if knowledge of this change could be valuable to users 
- [ ] Updated documentation to reflect any user-facing changes - in this repository
- [ ] Updated documentation to reflect any user-facing changes - PR to the guide that fixes existing documentation invalidated by this PR
- [x] Ran cargo fmt on the changes

Also, I'm a bit unsure the best way to chain together (3-4) structure types.  If there's a better way, please do let me know.

**Comment by Eliah-Lakhin** [comment]
@gurchetansingh Thank you very much for your contribution!

The code looks good, I'm happy to proceed with merging. But can you please also add a line to `CHANGELOG_VK_SYS` since there are changes in vk-sys subproject?

**Comment by gurchetansingh** [comment]
@Eliah-Lakhin thank you for reviewing!  I have updated the MR to add more detail to `CHANGELOG_VK_SYS`.

**Comment by Eliah-Lakhin** [comment]
@gurchetansingh Pull Request is merged! :)

**Comment by maximbaz** [comment]
Thank you so much @gurchetansingh for your work on this! I have been wishing for a while to see external memory being supported by vulkano!

> Import support will be added later. Support for external buffers and images can also be added later if someone needs it.

This is something that would be awesome to have. To be more specific, the use-case I'm after is to ask wlroots-based compositor to capture a frame of the entire screen by [exporting DMA-BUF](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-export-dmabuf-unstable-v1.xml) and then import this DMA-BUF into a Vulkan image (using `ImportMemoryFdInfoKHR`).

I was just curious if you were planning to implement import as well? I would be happy to help out with testing 🙂

**Comment by gurchetansingh** [comment]
Hi @maximbaz!

> Thank you so much @gurchetansingh for your work on this! I have been wishing for a while to see external memory being supported by vulkano!

Glad you like it and happy to do my part!  I've always felt Vulkano is a terrific crate and just needs a little TLC from it's users, now the legendary tomaka doesn't have the cycles to work on it anymore.  With a bit of auto-generation, magic is possible!

> I was just curious if you were planning to implement import as well? I would be happy to help out with testing 🙂.

Yes, already working on that!  Help testing would be terrific!  I'll CC you on the next MR hopefully sometime next week.

Another thing I'd love to see in Vulkano is VK_EXT_image_drm_format_modifier support.  Check out the Mesa MR:

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1466

If you're interested in compositors as I am, then maybe you could start adding support for that one 😉.

**Comment by maximbaz** [comment]
Ooh yes I'm following that MR for quite a while as well, had to disable DRM modifiers in my compositor so that I could get to play with my project at least _somehow_! Do I understand correctly that we have to wait until that MR is landed before we could even try to add this for Vulkano?

In any case I agree that supporting DRM format modifiers would be awesome to have, not sure if I will be able to make a meaningful code contribution, but at the very least I will be willing to help with some testing - lets see!

And thanks, looking forward to see your next MR! 🚀

**Comment by gurchetansingh** [comment]
> Do I understand correctly that we have to wait until that MR is landed before we could even try to add this for Vulkano?

Well, it is apart of the Vulkan spec and Vulkano doesn't necessarily require an open-source implementation.  I think you _should_ be able to build that MR and test via Vulkano cargo/unit tests.

> In any case I agree that supporting DRM format modifiers would be awesome to have, not sure if I will be able to make a meaningful code contribution.

If you have the cycles, I think you'll be able to figure it out ... with patience, friendship and teamwork anything is possible 🚀🚀🙂

**Pull request merged**
