### PR TITLE
#[derive(Copy, Clone)] on BufferlessDefinition and BufferlessVertices to allow cloning unfinished graphics pipeline builders

### PR DESCRIPTION
**Pull request by Arc-blroth**
* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [x] Ran `cargo fmt` on the changes

The title pretty much explains this small PR. This is useful whenever someone needs to define a lot of render passes with similar options but different shaders and vertex types.

### CODE REVIEW

**Comment by Eliah-Lakhin** [comment]
@Arc-blroth Thank you for the improvement! Can you fix merging conflicts, please?

**Comment by Eliah-Lakhin** [comment]
@Arc-blroth Sorry for disturbing. Are there any updates? I would like to proceed with merging, but the fix is blocked.

**Comment by Arc-blroth** [comment]
@Eliah-Lakhin Sorry for taking so long to fix merge conflicts 😓 Should be resolved now!

**Comment by Eliah-Lakhin** [comment]
@Arc-blroth Merged. Thanks!

**Pull request merged**
