### PR TITLE
Update winit to 0.13.1

### PR DESCRIPTION
**Pull request by branan**
Winit 0.13.0 has some fixes for window management on X11 that avoid some messy behavior with Vulkan surfaces (see tomaka/winit#434).

### CODE REVIEW

**Comment by branan** [comment]
Updated this to point to Winit 0.13.1 to pull in the x11-dl dependency fix

**Comment by francesca64** [comment]
...and now we're up to winit 0.15.0. Once again, no other changes needed.

**Comment by DancingBard** [comment]
Are there really no more changes needed to update to winit 0.15.0? I tried locally and got `error[E0599]: no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope` then... and I am wondering why atm. (Only change from winit ^0.11.0 right to ^0.15.0)

**Comment by rukai** [comment]
You will also need to change the version in the cargo.toml for vulkano-win.

**Comment by tomaka** [comment]
Thanks. This PR is no longer that relevant but it can't hurt to merge it.

**Pull request merged**
