### PR TITLE
glsl-to-spirv: Search `PATH` for `glslangValidator`.

### PR DESCRIPTION
**Pull request by the-kenny**
This PR extends `build.rs` for `glsl-to-spirv` to search `PATH` for `glslangValidator`. This makes it much easier to use the crate on my setup ([NixOS](https://nixos.org)).

The old behavior (for non-windows) still exists and is used as a fallback in case `glslangValidator` isn't in `PATH`.

### CODE REVIEW

**Comment by tomaka** [comment]
This is essentially #281 and #239

I think that searching for glslangValidator in PATH is wrong, but my opinion is not set in stone.

**Comment by the-kenny** [comment]
Oh I'm sorry - I didn't check existing PRs before implementing this (I was in a hurry to get it working).

I agree with some of your points in the other PR - it would be very annoying if users have an incompatible or outdated version in `PATH`. However, compiling it from source isn't very stable either. As mentioned in #281 it fails on NixOS because it can't find `std::isinf` (possible because NixOS uses LLVM? I'm not sure). 

Maybe it's possible to add a `feature` flag to `glsl-to-spirv` to enable this behavior as an opt-in?

**Comment by aristidb** [comment]
Why not use an environment variable VULKANO_GLSLANG_VALIDATOR_EXTERNAL_PATH. If it's not set, you can fall back to the current behavior. So then nobody can _accidentally_ use the wrong version of glslangValidator.

**Comment by the-kenny** [comment]
Thinking a bit more about it, I'd actually prefer a environment variable that's used at *runtime* even more. Maybe it's possible to change the behavior (or API?) so `glsl-to-spirv` can run `glslValidator` from `PATH` without copying/symlinking it at build-time?

**Comment by tomaka** [comment]
@the-kenny That's #291 and it requires tons of changes.

**Comment by Ralith** [comment]
@the-kenny I believe the NixOS build was fixed two months ago by 801a66e8565ef41b7bb7f06ce84d43822f69e7cd which has not yet been released on crates.io.

**Comment by the-kenny** [comment]
That's good to hear :) I still think supporting out-of-tree binaries is a
good idea to simplify the build process.

Am 27.11.2016 00:08 schrieb "Benjamin Saunders" <notifications@github.com>:

**Comment by rukai** [comment]
glsl-to-spirv is no more https://github.com/vulkano-rs/vulkano/pull/947

**Pull request closed without merging**
