### PR TITLE
Adds LICENSE-* files to crate subdirectories

### PR DESCRIPTION
**Pull request by jmacnak**
... so that the license files appear in downloaded crates.

### CODE REVIEW

**Comment by gurchetansingh** [comment]
CC: @Eliah-Lakhin @Rua

**Comment by gurchetansingh** [comment]
Hey, we're trying to integrate Vulkano to various projects and need this as first step.

**Comment by Rua** [comment]
Eliah is usually busy during the week, he reviews PRs on sundays.

**Comment by gurchetansingh** [comment]
So Rua, you've been making a lot of good changes lately.  Why don't you also become maintainer?

**Comment by AustinJ235** [comment]
Do links work for cargo publish? If so, I merge it.

**Comment by Eliah-Lakhin** [comment]
@jmacnak Please address the question from @AustinJ235, and we will proceed with merging. Thank you for your contribution!

**Comment by jmacnak** [comment]
I believe so as this is what futures-* is doing: https://github.com/rust-lang/futures-rs/blob/master/futures-core/LICENSE-MIT

**Comment by Eliah-Lakhin** [comment]
@jmacnak PR merged. Thanks for the improvement!

**Pull request merged**
