### PR TITLE
Rearrange descriptor set modules and types

### PR DESCRIPTION
**Pull request by Rua**
```markdown
- **Breaking** Major reorganisation of the `descriptor` module. Most importantly, its `descriptor_set` child is moved to the crate root and everything is placed under there. Full list of module changes:
  - `descriptor::descriptor_set::*` > `descriptor_set`.
  - `descriptor::descriptor::*` > `descriptor_set::layout`.
    - But `ShaderStages*` are moved to `pipeline::shader`.
  - `descriptor_set::UnsafeDescriptorSetLayout` > `descriptor_set::layout::DescriptorSetLayout` (renamed).
  - `descriptor_set::DescriptorSetDesc` > `descriptor_set::layout`.
  - `descriptor_set::{FixedSize*}` > `descriptor_set::fixed_size_pool`.
    - Re-exported `descriptor_set::FixedSizeDescriptorSetsPool`.
  - `descriptor_set::{Persistent*}` > `descriptor_set::persistent`.
    - Re-exported `descriptor_set::PersistentDescriptorSet`, `descriptor_set::PersistentDescriptorSetBuildError`, `descriptor_set::PersistentDescriptorSetError`.
  - `descriptor_set::{DescriptorPool*, DescriptorsCount, UnsafeDescriptorSetPool*}` > `descriptor_set::pool`.
  - `descriptor_set::{StdDescriptorPool*}` > `descriptor_set::pool::standard`.
    - Re-exported `descriptor_set::pool::StdDescriptorPool`.
  - `descriptor_set::{DescriptorWrite, UnsafeDescriptorSet}` > `descriptor_set::sys`.
  - `descriptor_set::collection` is now private.
```

This PR moves a lot of things around, but doesn't make any functional changes. The main change is that `descriptor_set` is now in the crate root, since this is the module that people need most often. Users don't need to mess with individual descriptors unless they are creating or working with descriptor set layouts, so that was made into its own module.

Instead of re-exporting everything from the `descriptor_set` module like before, only a few key types are now exported directly from `descriptor_set`, and the rest is placed in public submodules. For the structure of the submodules, I looked elsewhere in Vulkano for examples, in particular `buffer` (for the individual subtypes), `command_buffer` (for `pool` and `standard`) and `pipeline` (for `layout`).

The only change aside from moving things around is the rename of `UnsafeDescriptorSetLayout` to simply `DescriptorSetLayout`. This type isn't actually unsafe (even its documentation already said so), and since there are no other descriptor set layouts in Vulkano, it makes sense to give this type the simpler name.

### CODE REVIEW

**Comment by Eliah-Lakhin** [comment]
@Rua The code changes approved. Would you mind fixing merging conflicts, please?

**Comment by Rua** [comment]
Done.

**Comment by Eliah-Lakhin** [comment]
@Rua Needs another sync with `master` :)

**Comment by Rua** [comment]
Done again. :D

**Comment by Eliah-Lakhin** [comment]
@Rua It works fine, but `FixedSizeDescriptorSetsPool` and `FixedSizeDescriptorSetBuilder` are in in the different module levels. Maybe unify?

**Comment by Rua** [comment]
When you create a new builder, you call `next` on the pool. This doesn't require importing the type, so I figured it wasn't necessary to re-export it from a shorter path. The only type the user would construct from scratch, and therefore need to import, is the pool.

**Comment by Eliah-Lakhin** [comment]
That's true, but the user sometimes may need to refer the type itself sometimes too. Anyway, this is a minor thing.

**Comment by Eliah-Lakhin** [comment]
@Rua PR merged. Thank you!

**Pull request merged**
