### PR TITLE
segfaulting: DebugUtilsMessengerCallbackDataEXT::pMessageIdName may be null in debug callback

### PR DESCRIPTION
**Pull request by DaAitch**
Running on MacOS the `cargo run --bin debug` example is segfaulting (after fixing a layer problem: layer `VK_LAYER_LUNARG_standard_validation` doesn't exist on MoltenVK but it has to be `VK_LAYER_KHRONOS_validation`, but that's another point not in this scope).

- Source: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessengerCallbackDataEXT.html#VUID-VkDebugUtilsMessengerCallbackDataEXT-pMessageIdName-parameter
- `(*callback_data).pMessageIdName` is a null pointer for some debug callbacks (at least for two on my machine while testing)

* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [ ] Updated documentation to reflect any user-facing changes - in this repository
* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.
* [x] Ran `cargo fmt` on the changes

### CODE REVIEW

**Comment by Eliah-Lakhin** [comment]
@DaAitch Thank you for the fix. Can you add an entry to the changelog, please?

**Comment by DaAitch** [comment]
@Eliah-Lakhin Sure.

Do you have an idea for this string https://github.com/vulkano-rs/vulkano/pull/1487/files#diff-365d1440144c1c4c8329f5e8f963d7b182434c8d6bd74c25b67d80d303535b9bR105 I think "Unknown Layer" is not correct anymore. It's called `layer_prefix` but maybe sth. like`"Unknown message id name"` is better? I don't know.

**Comment by Eliah-Lakhin** [comment]
@DaAitch I think the more proper way of fixing it would be turning `Message::layer_prefix` into `Option`.

Also, in such case it will be a breaking change(which is fine), just we need to mention it in release logs. Something like: "**Breaking** `Message::layer_prefix` turned to Option to prevent segfaults when Vulkan message didn't provide `pMessageIdName` value"

**Comment by DaAitch** [comment]
@Eliah-Lakhin please check.

**Comment by Eliah-Lakhin** [comment]
@DaAitch Merged. Thank you!

**Pull request merged**
