### PR TITLE
doc: suggest brew on macOS

### PR DESCRIPTION
**Pull request by gibfahn**
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes

Having to hard-code the version is a bit of a pain, raised an issue in brew to discuss (https://github.com/Homebrew/homebrew-cask/issues/51330), but I'm not sure what the best solution is.

### CODE REVIEW

**Comment by rukai** [comment]
If the issue of having to specify the version in the environment variable is resolved then I can merge this.

**Comment by knappador** [comment]
I started to look at crafting some quick shell code but it looks like #1145  has superseded this PR?  @gibfahn I motion to close this PR unless #1145 missed something

**Comment by gibfahn** [comment]
Awesome, #1145 sounds great!

**Comment by knappador** [comment]
@gibfahn   I realized the issue that I linked was incorrect.  That PR was also closed without being merged.  You can find the composition of PR's that resulted in the updates to the readme in the blame:

https://github.com/vulkano-rs/vulkano/blame/master/README.md

**Pull request closed without merging**
