### PR TITLE
Copy buffer dimensions

### PR DESCRIPTION
**Pull request by Tetrel**
* [x] Added an entry to `CHANGELOG_VULKANO.md` or `CHANGELOG_VK_SYS.md` if knowledge of this change could be valuable to users
* [x] Updated documentation to reflect any user-facing changes - in this repository
* [ ] Updated documentation to reflect any user-facing changes - PR to the [guide](https://github.com/vulkano-rs/vulkano-www) that fixes existing documentation invalidated by this PR.
* [x] Ran `cargo fmt` on the changes

### CODE REVIEW

**Comment by Rua** [comment]
Could the function be named `copy_buffer_with_dimensions` instead? It's longer, but your name makes me think that it copies the dimensions of the buffer or something.

**Comment by AustinJ235** [comment]
@Rua suggestion seems to make the method name confusing. Other than that this seems like a sound idea. This is already possible with buffer slices, but this way would be less combersum.

**Comment by Tetrel** [comment]
Thank you for your response and feedback.
Yes, sure, changing the name is trivial. I chose the name in analogy to `copy_buffer_to_image_dimensions`, but since the buffers contain slices and the idea is to allow copying subslices I would rather suggest the name `copy_buffer_range` or `copy_buffer_with_range`.

**Review by Eliah-Lakhin — APPROVED** [review]

**Comment by Eliah-Lakhin** [comment]
@Tetrel I merged the PR. Thank very much for your contribution! And I'm sorry for delay with review.

Personally I don't see any issues with proposed naming, but we can change it later if needed. We are still on the version behind `v1.0`, so changes in public API names would be fine I think.

**Pull request merged**
