### PR TITLE
Reimplement Generic Impl for BufferAcces, TypedBufferAccess & ImageAccess

### PR DESCRIPTION
**Pull request by AustinJ235**
This reverts changes made in https://github.com/vulkano-rs/vulkano/pull/1739 that removed generic implementations for `BufferAccess`, `TypedBufferAccess`, & `ImageAccess`.

When creating wrappers for these traits, it is currently not possible to wrap them in `Arc<_>`.

- i.e. `impl ImageAccess for SomeType` will not implement `ImageAccess` for `Arc<SomeType>`.

Fixes: https://github.com/vulkano-rs/vulkano/issues/1773

### CODE REVIEW

**Comment by Rua** [comment]
Do you want to release this as 0.27.1 before any other PRs are merged?

**Review by Eliah-Lakhin — APPROVED** [review]

**Comment by Eliah-Lakhin** [comment]
I think it would be a good idea to make a minor release with this revert.

**Comment by Eliah-Lakhin** [comment]
@AustinJ235 PR approved. I will leave it at your hands to confirm if it fixes the issue in your project, and to merge it. Then you can make a minor release(I LMK, and I will do it).

I will hold with other PRs merging until we resolve this one.

**Comment by AustinJ235** [comment]
Merged and released.

**Pull request merged**
